# Generated by Django 3.2.13 on 2023-11-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_location_speeddata_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ThrottleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throttle', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='T3Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='T2Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='T1Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Switch_EncodingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Switch_Encoding', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='RPMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Motor_StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motor_State', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Meter_CountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meter_Count', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='M_Error_StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Error_Status', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CruiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='BrakeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
    ]
