# Generated by Django 3.2.13 on 2023-11-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_brakedata_cruisedata_currentdata_energydata_m_error_statusdata_meter_countdata_motor_statedata_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brakedata',
            old_name='brake',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='cruisedata',
            old_name='cruise',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='currentdata',
            old_name='current',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='energydata',
            old_name='energy',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='m_error_statusdata',
            old_name='M_Error_Status',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='meter_countdata',
            old_name='Meter_Count',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='motor_statedata',
            old_name='Motor_State',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='powerdata',
            old_name='power',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='rpmdata',
            old_name='rpm',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='speeddata',
            old_name='speed',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='switch_encodingdata',
            old_name='Switch_Encoding',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='t1data',
            old_name='t1',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='t2data',
            old_name='t1',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='t3data',
            old_name='t1',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='throttledata',
            old_name='throttle',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='voltagedata',
            old_name='voltage',
            new_name='data',
        ),
        migrations.CreateModel(
            name='S_Error_StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
        migrations.CreateModel(
            name='P_Error_StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
        ),
    ]
