# Generated by Django 3.2.13 on 2023-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_auto_20231116_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('mqtt', 'mqtt'), ('ws', 'ws')], max_length=30)),
                ('event', models.CharField(choices=[('connect', 'connect'), ('disconnect', 'disconnect'), ('receive_message', 'receive_message')], max_length=30)),
                ('message', models.TextField()),
                ('error', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
