# Generated by Django 3.2.13 on 2023-11-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_mqtterrors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MQTTErrors',
            new_name='MQTTError',
        ),
    ]
