# Generated by Django 3.2.13 on 2023-11-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_rename_mqtterrors_mqtterror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brakedata',
            options={'verbose_name_plural': '    Brake Data'},
        ),
        migrations.AlterModelOptions(
            name='cruisedata',
            options={'verbose_name_plural': '    Cruise Data'},
        ),
        migrations.AlterModelOptions(
            name='currentdata',
            options={'verbose_name_plural': '  Current Data'},
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'verbose_name_plural': '  Energy Data'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': ' Location Data'},
        ),
        migrations.AlterModelOptions(
            name='m_error_statusdata',
            options={'verbose_name_plural': '    M Error Status Data'},
        ),
        migrations.AlterModelOptions(
            name='meter_countdata',
            options={'verbose_name_plural': '    Meter Count Data'},
        ),
        migrations.AlterModelOptions(
            name='motor_statedata',
            options={'verbose_name_plural': '    Motor State Data'},
        ),
        migrations.AlterModelOptions(
            name='p_error_statusdata',
            options={'verbose_name_plural': '  P Error Status Data'},
        ),
        migrations.AlterModelOptions(
            name='powerdata',
            options={'verbose_name_plural': '  Power Data'},
        ),
        migrations.AlterModelOptions(
            name='rpmdata',
            options={'verbose_name_plural': '    RPM Data'},
        ),
        migrations.AlterModelOptions(
            name='s_error_statusdata',
            options={'verbose_name_plural': '   S Error Status Data'},
        ),
        migrations.AlterModelOptions(
            name='speeddata',
            options={'verbose_name_plural': ' Speed Data'},
        ),
        migrations.AlterModelOptions(
            name='switch_encodingdata',
            options={'verbose_name_plural': '   Switch Encoding Data'},
        ),
        migrations.AlterModelOptions(
            name='t1data',
            options={'verbose_name_plural': '  T1 Data'},
        ),
        migrations.AlterModelOptions(
            name='t2data',
            options={'verbose_name_plural': '  T2 Data'},
        ),
        migrations.AlterModelOptions(
            name='t3data',
            options={'verbose_name_plural': '  T3 Data'},
        ),
        migrations.AlterModelOptions(
            name='throttledata',
            options={'verbose_name_plural': '    Throttle Data'},
        ),
        migrations.AlterModelOptions(
            name='voltagedata',
            options={'verbose_name_plural': '  Voltage Data'},
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='trip',
            field=models.ForeignKey(blank=None, default=1, on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip'),
        ),
        migrations.AddField(
            model_name='mqtterror',
            name='trip',
            field=models.ForeignKey(blank=None, default=1, on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip'),
        ),
    ]
