# Generated by Django 4.2.7 on 2024-01-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_auto_20231125_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
