# Generated by Django 4.2.7 on 2024-01-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0010_mqtterror_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtterror',
            name='ip_address',
        ),
    ]
