# Generated by Django 4.2.7 on 2024-02-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0012_trip_start_trip_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stop',
            field=models.DateTimeField(blank='', default='', null=''),
        ),
    ]
