# Generated by Django 4.2.7 on 2024-02-01 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0013_alter_trip_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stop',
            field=models.DateTimeField(blank=datetime.datetime(1969, 12, 31, 16, 0), default=datetime.datetime(1969, 12, 31, 16, 0), null=datetime.datetime(1969, 12, 31, 16, 0)),
        ),
    ]
