# Generated by Django 4.2.7 on 2024-03-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0015_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_error_statusdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='t1data',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='t2data',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='t3data',
            name='trip',
        ),
        migrations.DeleteModel(
            name='EnergyData',
        ),
        migrations.DeleteModel(
            name='P_Error_StatusData',
        ),
        migrations.DeleteModel(
            name='T1Data',
        ),
        migrations.DeleteModel(
            name='T2Data',
        ),
        migrations.DeleteModel(
            name='T3Data',
        ),
    ]
