# Generated by Django 4.2.7 on 2024-03-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0016_remove_p_error_statusdata_trip_remove_t1data_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  Acceleration Data',
            },
        ),
        migrations.CreateModel(
            name='Blinker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '   Blinkers',
            },
        ),
        migrations.CreateModel(
            name='Gyro_x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  Gyro X',
            },
        ),
        migrations.CreateModel(
            name='Gyro_y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  Gyro Y',
            },
        ),
        migrations.CreateModel(
            name='Gyro_z',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  Gyro Z',
            },
        ),
        migrations.CreateModel(
            name='Magnetometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  Magnetometer',
            },
        ),
        migrations.RemoveField(
            model_name='powerdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='s_error_statusdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='switch_encodingdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='voltagedata',
            name='trip',
        ),
        migrations.DeleteModel(
            name='CurrentData',
        ),
        migrations.DeleteModel(
            name='PowerData',
        ),
        migrations.DeleteModel(
            name='S_Error_StatusData',
        ),
        migrations.DeleteModel(
            name='Switch_EncodingData',
        ),
        migrations.DeleteModel(
            name='VoltageData',
        ),
    ]
